config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root 'users#index'
end

app/models/good_customers.rb
class GoodCustomers
  include Delayed::RecurringJob
  run_every 7.days
  run_at '12:00am'
  timezone 'US/Pacific'
  queue 'good customers'

  def perform
    winners_rates = User.select("users.id, users.name, users.email, sum(reviews.rate) as rate").
      where('reviews.created_at > ?', 1.week.ago).joins(:reviews).group("id").having("sum(reviews.rate) > ?", 80)
    UserMailer.good_customers(winners_rates).deliver_now
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  validates :rate, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :validatable, :trackable
  validates :name, presence: true, length: {minimum: 4}
  has_many :reviews, dependent: :destroy

end

app/models/user_remainder.rb
class UserRemainder
  include Delayed::RecurringJob
  run_every 1.day
  run_at '12:00am'
  timezone 'US/Pacific'
  queue 'user remainder'

  def perform
    start_interval, end_interval = [3.day, 1.day].map{|time| DateTime.now.ago(time).at_midnight.change(offset: 0)}
    users = User.select("name, email").
      where(last_sign_in_at: [start_interval..end_interval, start_interval - 2.days..end_interval - 3.days])
    UserMailer.notification(users).deliver_now
  end
end

app/models/weekly_winners.rb
class WeeklyWinners
  include Delayed::RecurringJob
  run_every 7.days
  run_at '12:00am'
  timezone 'US/Pacific'
  queue 'weekly winners'

  def perform
    winners_rates = User.select("users.id, users.name, sum(reviews.rate) as rate").joins(:reviews).group("id").order("rate desc").limit(10)
    UserMailer.weekly_winners(winners_rates).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ActionController::Live
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    # select kind, sum(value) from records group by kind having count(kind) > 1 order by kind;
    # @records = Record.select('kind, sum(value) as val').group('kind').having("count(kind) > ?", 1).order('time')
    @records = Record.select('kind, value as val, time').where("id != ? AND id != 3", 6).order('time desc').limit(2)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

def stream
  1_000_000.times do |i|
    response.stream.write "This is line #{i}\n"
  end
ensure
  response.stream.close
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MindStudios</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Mind Studios 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, html: { class: "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :email, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-default' %>
          <%= link_to 'Destroy', user_path(user), method: 'delete', data: { confirm:  'Are you sure?'}, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong>Email:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<%= link_to 'Back', users_path, class: 'btn btn-default' %>
<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-default' %>
<%= link_to 'Destroy', user_path(@user), method: 'delete', data: { confirm:  'Are you sure?'}, class: 'btn btn-danger' %>